
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-grid}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
      POSTGRES_USER: ${POSTGRES_USER:-main}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> meilisearch/search-bundle ###
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.0}
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}
    volumes:
      - meilisearch_data:/meili_data
###< meilisearch/search-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###


###> meilisearch/search-bundle ###
  meilisearch_data:
###< meilisearch/search-bundle ###
